spring.datasource.url=jdbc:mysql://localhost:3306/eventopia_db
spring.datasource.username=root
spring.datasource.password=Vishal@4995

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8081
